const art = [
{
  "link": "https://i.imgur.com/681PUyI.jpg",
  "title": "Luxury Condo Lobby",
  "year": 2017,
  "media": "collage made with discarded envelopes & credit card offers",
  "dims": `22"x30"`,
  "availableForSale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside.The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/mooEObi.jpg",
  "title": "Drop Ceiling",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/CpQf31m.jpg",
  "title": "Trees Piercing Clouds",
  "year": 2012,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/SXdLEtP.jpg",
  "title": "Office Solution",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/0SY8xMv.jpg",
  "title": "Ready to Assemble",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/9Jc8hfj.jpg",
  "title": "Pile of Leaves in Cubicle",
  "year": 2015,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/3hLAn2f.jpg",
  "title": "You Deserve More",
  "year": 2013,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": false,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/Odfh9mD.jpg",
  "title": "A New Every Day",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/2d9YKH3.jpg",
  "title": "Rainbow Security Grass",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "dims": `fix dims`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/yStfCmg.jpg",
  "title": "Scraps & Daisies",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "dims": `15"x11"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/1nsceYO.jpg",
  "title": "Scraps & Daisies #02",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "dims": `15"x11"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/x4lJ3kv.jpg",
  "title": "Silk Lobby Ranunculus 01",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "dims": `16"x20"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/Jomo2F4.jpg?1",
  "title": "Blue Forest Floor",
  "year": 2013,
  "media": "collage made with discarded envelopes",
  "dims": `16"x20"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/pcJEOpb.jpg",
  "title": "Live Gloriously",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "dims": "20\"x29\"",
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/MFZdNd7.jpg",
  "title": "Fake Lobby Arrangements",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "dims": `22"x30"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/DIJ63na.jpg",
  "title": "Silk Lobby Ranunculus #03",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "dims": "10\"x8\"",
  "availableForSale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/OvKeaW4.jpg",
  "title": "Silk Lobby Bird of Paradise #02",
  "year": 2015,
  "media": "collage made with discarded envelopes",
  "dims": `15"x11"`,
  "availableForSale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/GvoxW2M.jpg",
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "dims": `780'`,
  "availableForSale": false,
  "price": "",
  "location": "n/a - temporary",
  "category": "public art",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/tfikUEj.jpg",
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "dims": `780'`,
  "availableForSale": false,
  "price": "",
  "location": "n/a - temporary",
  "category": "public art",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/JSw7FEi.jpg",
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "dims": `780'`,
  "availableForSale": false,
  "price": "",
  "location": "n/a - temporary",
  "category": "public art",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/C7IfM2n.jpg",
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "dims": `780'`,
  "availableForSale": false,
  "price": "",
  "location": "n/a - temporary",
  "category": "public art",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/WZVfCs6.jpg",
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "dims": `40'x4'`,
  "availableForSale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "category": "public art",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/10eBQTS.jpg",
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "dims": `40'x4'`,
  "availableForSale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "category": "public art",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": false,
},
{
  "link": "https://i.imgur.com/16Uik9x.jpg",
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "dims": `40'x4'`,
  "availableForSale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "category": "public art",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/svHGqi8.jpg",
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "dims": `40'x4'`,
  "availableForSale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "category": "public art",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/3lBcVXv.jpg",
  "year": "2014",
  "media": "printed tag",
  "title": "toaster and drawers",
  "category": "curbside tag",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/t37rQKa.jpg",
  "year": "2014",
  "media": "printed tag",
  "title": "toaster",
  "category": "curbside tag",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/OsUXs3K.jpg",
  "year": "2014",
  "media": "unlimited edition printed tag",
  "title": "dishwasher",
  "category": "curbside tag",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/hKwxhAp.jpg",
  "title": "Little Brown Barf Bag",
  "year": "",
  "media": "unlimited edition screenprint",
  "dims": "",
  "availableForSale": true,
  "price": "$7",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/JqfXz4Q.jpg",
  "title": "ATM/Outhouse",
  "year": "2010",
  "media": "limited edition screenprint",
  "dims": "",
  "availableForSale": true,
  "price": "",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "portrait",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/h3kRid9.jpg",
  "title": "Hearth",
  "year": "2010",
  "media": "limited edition screenprint",
  "dims": "",
  "availableForSale": true,
  "price": "",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "portrait",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/X76gDEu.jpg?4",
  "title": "Deposits Accepted",
  "year": "",
  "media": "limited edition screenprint",
  "dims": "",
  "availableForSale": true,
  "price": "",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "portrait",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/euN6hs4.jpg",
  "title": "Oh Shit",
  "year": "2004",
  "media": "limited edition linoleum-cut on vellum",
  "dims": `18"x12"`,
  "availableForSale": true,
  "price": "sold out",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "portrait",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/UdjZeLU.jpg",
  "title": "Self Portrait as a Marshmallow",
  "year": "2007",
  "media": "limited edition screenprint",
  "dims": "",
  "availableForSale": true,
  "price": "sold out",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "square",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/sdaLvNj.jpg",
  "title": "Sunbeam",
  "year": "2007",
  "media": "limited edition aquatint with crush photovoltaic cells",
  "dims": `12"x15"`,
  "availableForSale": true,
  "price": "$400",
  "location": "flat files",
  "category": "print",
  "statement": "",
  "imageShape": "landscape",
  "includeingallery": true,
}

]

export default art
