const artEnvelopeCollages = [
{
  "title": "Luxury Condo Lobby",
  "year": 2017,
  "media": "collage made with discarded envelopes & credit card offers",
  "link": "https://i.imgur.com/681PUyI.jpg",
  "dims": `22"x30"`,
  "available-for-sale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "<div class=\"ad_box\"><img class=\"banner\" src=\"some_ad.png\" alt=\"\" \/><h3>&quot;Hot&quot; Items <\/h3> <br \/> <ul id=\"items\" \/><\/div>",
  "includeingallery": true,
},
{
  "title": "Drop Ceiling",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/mooEObi.jpg",
  "dims": `22"x30"`,
  "available-for-sale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Office Solution",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/SXdLEtP.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Ready to Assemble",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/0SY8xMv.jpg",
  "dims": `22"x30"`,
  "available-for-sale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Pile of Leaves in Cubicle",
  "year": 2015,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/9Jc8hfj.jpg",
  "dims": `22"x30"`,
  "available-for-sale": true,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "You Deserve More",
  "year": 2013,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/3hLAn2f.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "$2,000",
  "location": "flat files",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Trees Piercing Clouds",
  "year": 2012,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/CpQf31m.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "A New Every Day",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/Odfh9mD.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Rainbow Security Grass",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/2d9YKH3.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Fake Lobby Arrangements",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/MFZdNd7.jpg",
  "dims": `22"x30"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Scraps & Daisies",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/yStfCmg.jpg",
  "dims": `15"x11"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": false,
},
{
  "title": "Scraps & Daisies #02",
  "year": 2017,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/1nsceYO.jpg",
  "dims": `15"x11"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": false,
},
{
  "title": "Silk Lobby Ranunculus 01",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/x4lJ3kv.jpg",
  "dims": `16"x20"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Blue Forest Floor",
  "year": 2013,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/Jomo2F4.jpg?1",
  "dims": `16"x20"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Live Gloriously",
  "year": 2014,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/pcJEOpb.jpg",
  "dims": "20\"x29\"",
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": true,
},
{
  "title": "Silk Lobby Ranunculus #03",
  "year": 2016,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/DIJ63na.jpg",
  "dims": "10\"x8\"",
  "available-for-sale": false,
  "price": "not for sale",
  "location": "private collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": false,
},
{
  "title": "Silk Lobby Bird of Paradise #02",
  "year": 2015,
  "media": "collage made with discarded envelopes",
  "link": "https://i.imgur.com/OvKeaW4.jpg",
  "dims": `15"x11"`,
  "available-for-sale": false,
  "price": "not for sale",
  "location": "Permanent Collection of the NYU Langone Medical Center Art Program and Collection",
  "category": "envelope collages",
  "statement": "Security envelopes are used to camouflage sensitive and private documents. Their decorative patterns make it impossible to read what is inside. The secrets contained within these envelopes form the dull, bureaucratic infrastructure for contemporary life. The artist creates landscapes with this material diverted from the waste-stream. These collages represent a fantasy in which the material of the reliable, boring disappointments of life, are transformed into a means of escape.",
  "includeingallery": false,
},
]

export default artEnvelopeCollages
