const otherArt = [
{
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "link": "https://i.imgur.com/GvoxW2M.jpg",
  "dims": `780'`,
  "available-for-sale": false,
  "price": "",
  "location": "n/a - temporary",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "includeingallery": true,
},
{
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "link": "https://i.imgur.com/tfikUEj.jpg",
  "dims": `780'`,
  "available-for-sale": false,
  "price": "",
  "location": "n/a - temporary",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "includeingallery": true,
},
{
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "link": "https://i.imgur.com/JSw7FEi.jpg",
  "dims": `780'`,
  "available-for-sale": false,
  "price": "",
  "location": "n/a - temporary",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "includeingallery": false,
},
{
  "title": "Cats in Repose",
  "year": "2016",
  "media": "Painted pedestrian barrier. East 161st Street between Gerard Avenue and Concourse, The Bronx",
  "link": "https://i.imgur.com/C7IfM2n.jpg",
  "dims": `780'`,
  "available-for-sale": false,
  "price": "",
  "location": "n/a - temporary",
  "statement": "Cats in Repose celebrates the wide variety and creativity of feline resting positions. This suite of lounging and napping cat silhouettes represents luxury, leisure and laziness, and contrasts sharply with the frenetic hum of movement on city streets.",
  "includeingallery": true,
},
{
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "link": "https://i.imgur.com/WZVfCs6.jpg",
  "dims": `40'x4'`,
  "available-for-sale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "link": "https://i.imgur.com/10eBQTS.jpg",
  "dims": `40'x4'`,
  "available-for-sale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "statement": "",
  "includeingallery": false,
},
{
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "link": "https://i.imgur.com/16Uik9x.jpg",
  "dims": `40'x4'`,
  "available-for-sale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Security Grass",
  "year": "2018",
  "media": "Printed vinyl affixed to HESCO barrier, Red Hook Brooklyn, temporary",
  "link": "https://i.imgur.com/svHGqi8.jpg",
  "dims": `40'x4'`,
  "available-for-sale": false,
  "price": "",
  "location": "Red Hook Brooklyn. Temporary",
  "statement": "",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/3lBcVXv.jpg",
  "year": "2014",
  "media": "printed tag",
  "title": "toaster and drawers",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/t37rQKa.jpg",
  "year": "2014",
  "media": "printed tag",
  "title": "toaster",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "includeingallery": true,
},
{
  "link": "https://i.imgur.com/OsUXs3K.jpg",
  "year": "2014",
  "media": "unlimited edition printed tag",
  "title": "dishwasher",
  "statement": "The Curbside Object Status Tag facilitates the smooth operation of the informal sidewalk gift economy. Those who place objects on the curb for people to pick up, may now indicate the condition of the object to people by ticking the appropriate box on the tag. People who are considering picking up an object off the street no longer have to wonder about the condition of said object.Contact me if you’d like some tags or if you’d like to submit user images.",
  "includeingallery": true,
},
{
  "title": "ATM/Outhouse",
  "year": "2010",
  "media": "limited edition screenprint",
  "link": "https://i.imgur.com/JqfXz4Q.jpg",
  "dims": "",
  "available-for-sale": true,
  "price": "",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Hearth",
  "year": "2010",
  "media": "limited edition screenprint",
  "link": "https://i.imgur.com/h3kRid9.jpg",
  "dims": "",
  "available-for-sale": true,
  "price": "",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "",
  "year": "",
  "media": "limited edition screenprint",
  "link": "https://i.imgur.com/X76gDEu.jpg?4",
  "dims": "",
  "available-for-sale": true,
  "price": "",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Little Brown Barf Bag",
  "year": "",
  "media": "unlimited edition screenprint",
  "link": "https://i.imgur.com/hKwxhAp.jpg",
  "dims": "",
  "available-for-sale": true,
  "price": "$7",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Self Portrait as a Marshmallow",
  "year": "2007",
  "media": "limited edition screenprint",
  "link": "https://i.imgur.com/UdjZeLU.jpg",
  "dims": "",
  "available-for-sale": true,
  "price": "$7",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
},
{
  "title": "Sunbeam",
  "year": "2007",
  "media": "limited edition aquatint with crush photovoltaic cells",
  "link": "https://i.imgur.com/sdaLvNj.jpg",
  "dims": "",
  "available-for-sale": true,
  "price": "$200",
  "location": "flat files",
  "statement": "",
  "includeingallery": true,
}






]

export default otherArt
